name: Ruff lint
permissions:
  contents: write

on:
  push:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-lint-v1
        restore-keys: |
          ${{ runner.os }}-lint-v1

    - name: Install Ruff
      run: |
        pip install ruff

    - name: Lint Python files
      run: |
        ruff check . --fix
    
    - name: Push when lint errors are fixed
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'Fix lint errors'
          git push
        fi