name: Send Discord Message

on:
  push:

jobs:
  send-discord-message:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Message
        run: |
          curl -X POST -H "Content-Type: application/json" -d '${{ github.actor}}が${{ github.event.repository.name }}にpushした！ありがとう！' ${{ secrets.DISCORD_WEBHOOK_URL }}